[package]
name = "jemallocator"
version = "0.1.0"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
license = "MIT/Apache-2.0"
readme = "README.md"
keywords = ["allocator"]
repository = "https://github.com/alexcrichton/jemallocator"
homepage = "https://github.com/alexcrichton/jemallocator"
documentation = "http://alexcrichton.com/jemallocator"
description = """
A Rust allocator backed by jemalloc
"""

[dependencies]
jemalloc-sys = { path = "jemalloc-sys", version = "0.1.0" }
libc = { version = "0.2.8", default-features = false }
