[build.env]
passthrough = [
    "RUST_BACKTRACE",
    "RUST_TEST_THREADS",
    "RUST_TEST_NOCAPTURE",
    "JEMALLOC_SYS_RUN_TESTS",
    "JEMALLOC_SYS_VERIFY_CONFIGURE",
]

[target.aarch64-unknown-linux-gnu]
image = "jemallocator/aarch64-unknown-linux-gnu:0.1"