[package]
name = "jemalloc-sys"
version = "0.1.0"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
build = "build.rs"
links = "jemalloc"

[dependencies.libc]
git = "https://github.com/alexcrichton/libc"
features = ["no-std"]
branch = "no-std"

[build-dependencies]
gcc = "0.3"
